### ISSUE TITLE
ソース公開

### ISSUE THREAD

**Issue by Petitsurume** [Petitsurume/MUCS#3]
* [x] サーバー未公開部分からdevelop部分へのpush
* [x] | ブランチを作成してpush
* [x] | developにPull Requestする
* [x] | Mergeする
* [ ] Pull Requestをサーバー未公開部分に展開
* [x] developブランチをサーバー未公開部分に公開
* [x] masterブランチをhttp://surume.exout.net/mucs/client/ に公開

**Comment by AyaMorisawa** [comment]
You should write like this:
```md
* [ ] サーバー未公開部分からdevelop部分へのpush
* [ ] Pull Requestをサーバー未公開部分に展開
* [ ] developブランチをサーバー未公開部分に公開
* [ ] masterブランチをhttp://surume.exout.net/mucs/client/に公開
```

**Comment by Petitsurume** [comment]
@AyaMorisawa thx

**Comment by Petitsurume** [comment]
Pull Requestsは展開しないことにした
